apiVersion: v1
kind: Service
metadata:
  name: neoncat-hello
  namespace: default
  labels:
    app: neoncat-hello
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    app: neoncat-hello

